### ISSUE TITLE
接口调用

### ISSUE THREAD

**Issue by pigbrother** [AnyListen/tianruoocr_last#2]
接口能免费多少次 老铁有研究吗

**Comment by AnyListen** [comment]
正在研究新接口，免费的接口如果每个人自己申请密钥的话，几乎都是够用的

**Comment by pigbrother** [comment]
阿里云的 五百个 百度的五百个  搜狗的地址有没 发一个 只看到他们AI的

**Comment by AnyListen** [comment]
https://deepi.sogou.com
